name: CI

on:
  push:
    branches: [ 1.3.70 ] # switch to master once finished testing
  pull_request:
    branches: [ 1.3.70 ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Build and test
      run: ./gradlew clean build check
